name: Issue Assignment
on:
  issues:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto Assign issue'
        uses: pozil/auto-assign-issue@v1.0.3
        with:
          repo-token: ${{ secrets.ALL_ACCESS }}
          assignees: hassanarifibm
