name: Send LGTM Reaction
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: micnncim/action-lgtm-reaction@master
          env:
            GITHUB_TOKEN: ${{ secrets.ALL_ACCESS }}
          with:
            trigger: '[".*looks good to me.*"]'
            overide: true
            source: 'giphy'
